Feature/15 add gh action to execute python tests
gridscale/gridscale_api_client_python pull request #16
Opened 2022-03-17 17:21 UTC by jonathanlutterbeck

Added a github action to test all files.

2022-03-18 10:34 UTC, bkircher requested changes
Cool, thanks for working on this. Can you take a look at two requested changes above?

As a side note: If you run flake8 or pylint on your terminal in this project, you see that there is no proper config for either of these tools and there are lots of warnings. I think it is a good next thing to work on, isn't it? :smile:  I will create an issue for this.

As we can see, there is still a Travis CI job executed, besides the GH Action. I forgot about this. Let's just ignore this for now :sweat_smile: 

The Travis CI thing fails when it tries to push a package to PyPI because of missing authentication tokens. Totally reasonable, since we don't want to push to PyPI from PR branches. I think, in the mid-term we should get rid of Travis CI and only use GH Actions. @Aldemuro @begotxe any thoughts on this?

2022-03-18 10:34 UTC, bkircher commented on .github/workflows/pytest.yml
> +        pip install flake8 pytest
Please remove this line. pytest and things is installed via dev-requirements.txt

2022-03-18 10:34 UTC, bkircher commented on .github/workflows/pytest.yml
> +        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
You can remove the test here if dev-requirements.txt exists. Just assume it does :smile: If it doesn't this pipeline fails, which is good.

2022-03-18 11:36 UTC, bkircher commented
Created a new issue for that linter stuff: https://github.com/gridscale/gridscale_api_client_python/issues/17

2022-03-21 14:23 UTC, jonathanlutterbeck commented
The requested changes have been made. Check here: [https://github.com/gridscale/gridscale_api_client_python/commit/67fdc34a76f69e56dba7e7da93c740a79ca80946#](url)

2022-03-21 14:30 UTC, bkircher approved these changes

2022-03-21 14:32 UTC, merged

2022-03-21 14:32 UTC, bkircher commented
Thanks! Merged